export type Product = {
  slug: string;
  name: string;
  client: string;
  description: string;
  url: string;
  width: number;
  height: number;
};

// Auto-generated by scripts/generate-product-manifest.mjs
// Fill in client/description per product, then leave the rest alone.
export const products: Product[] = [
  {
    slug: "hover",
    name: "HOVER",
    client: "Bio-mimetic Design",
    description: "A biomimicry driven bicycle helmet inspired by the marvelous spatuletail hummingbird, translating its agility, lightweight form, and aerodynamic efficiency into a safer, performance focused cycling experience",
    url: "products/hover.png",
    width: 1200,
    height: 700,
  },
  {
    slug: "vayu",
    name: "VAYU",
    client: "Smart Air Purifier",
    description: "VAYU is a lifestyle integrated air purifier that combines intuitive physical feedback, automation, and seamless spatial integration to transform air purification into an effortless everyday experience.",
    url: "products/vayu.png",
    width: 487,
    height: 319,
  },
  {
    slug: "loop",
    name: "LOOP",
    client: "Modular Gardening",
    description: "A compact modular gardening concept built around flexibility and simplicity. The system consists of interchangeable planter units that can be arranged, expanded, and adapted to different spaces—making urban gardening more accessible and visually integrated into everyday environments.",
    url: "products/loop.png",
    width: 1980,
    height: 1200,
  },
  {
    slug: "rahee",
    name: "RAHEE",
    client: "Smart Navigation & Assistant",
    description: "RAHEE is a smart navigation and assistance concept designed to make everyday movement more intuitive and independent. Combining physical feedback, intelligent automation, and seamless spatial interaction, the system helps guide users through their environment with clear, responsive cues.",
    url: "products/rahee.png",
    width: 571,
    height: 318,
  },
  {
    slug: "opulence",
    name: "OPULENCE",
    client: "Phygital Entertainment System",
    description: "Opulence is a mixed reality in-flight entertainment system designed for premium air travel. By combining an MR headset with modular interactive cubes, it transforms conventional entertainment into immersive spatial experiences for work, play, and relaxation.",
    url: "products/opulence.png",
    width: 2000,
    height: 1900,
  },
    {
    slug: "atomo",
    name: "Atomo",
    client: "AI System",
    description: "A compact enclosure designed to protect AI computing hardware while ensuring efficient thermal management and a clean, functional aesthetic.",
    url: "products/atomo.png",
    width: 3840,
    height: 2160,
  },
      {
    slug: "flo",
    name: "Flo",
    client: "Air Purifer designed for NOISE",
    description: "FLO is an air purification concept designed to address both air quality and everyday noise. Its form integrates filtration and acoustic considerations into a single product, creating a quieter and more comfortable indoor environment through a clean, contemporary design.",
    url: "products/flo.png",
    width: 1916,
    height: 1448,
  },
  {
    slug: "prism-planter",
    name: "PRISM PLANTER",
    client: "Geometric planter",
    description: "A geometric planter inspired by sharp, faceted forms that transforms everyday greenery into a contemporary decorative statement.",
    url: "products/prism_planter.png",
    width: 300,
    height: 440,
  },
  {
    slug: "aroma-sphere",
    name: "AROMA SPHERE",
    client: "Fragrance diffuser",
    description: "A minimal fragrance diffuser designed to hold camphor or aroma blocks, creating a calming atmosphere while blending seamlessly into modern living spaces.",
    url: "products/aroma_sphere.png",
    width: 1920,
    height: 1080,
  },
  {
    slug: "arka",
    name: "ARKA",
    client: "Convertible Task Light",
    description: "Árka is a convertible glare-free task light designed for modern workspaces, offering both focused and ambient illumination through an adaptable, space-efficient design that prioritizes user comfort and sustainability.",
    url: "products/arka.png",
    width: 1080,
    height: 1080,
  },
  {
    slug: "astra-core",
    name: "ASTRA CORE",
    client: "Rugged military powerbank",
    description: "A rugged, high-capacity power bank built for demanding outdoor and tactical environments, offering durability without compromising portability.",
    url: "products/astra_core.png",
    width: 1920,
    height: 1080,
  },
  {
    slug: "isometric-room-visualization",
    name: "Isometric Room Visualization",
    client: "3D Room visualization",
    description: "A detailed 3D visualization project showcasing realistic lighting, materials, and spatial storytelling through an isometric interior environment.",
    url: "products/iso_room.png",
    width: 1080,
    height: 1080,
  },
     {
    slug: "stride",
    name: "STRIDE",
    client: "hard-shell luggage",
    description: "Stride is a modern hard-shell luggage concept designed for effortless travel. Featuring a durable ribbed exterior, smooth mobility, and a clean, contemporary form, it balances functionality with a refined visual identity.",
    url: "products/stride.png",
    width: 1080,
    height: 1080,
  },
  {
    slug: "rinox",
    name: "RINOX",
    client: "Rhino inspired gaming console",
    description: "A bold gaming console concept inspired by the strength and form of a rhinoceros, translating nature into a powerful futuristic design language.",
    url: "products/rinox.png",
    width: 1920,
    height: 1080,
  },
  {
    slug: "orbit-one",
    name: "ORBIT ONE",
    client: "satellite communication device",
    description: "A concept satellite communication device designed for reliable connectivity in remote environments, combining durability with intuitive usability.",
    url: "products/orbit_one.png",
    width: 1920,
    height: 1920,
  },
{
  slug: "respira",
  name: "RESPIRA",
  client: "Air Purifier Designed for Indian Homes",
  description:
    "Respira is an air purifier designed to seamlessly blend into Indian homes through thoughtful aesthetics and user-centric functionality. It features an intuitive filter replacement system and a detachable planter that brings together cleaner air, modularity, and a stronger connection with nature.",
  url: "products/respira_render.png",
  width: 1400,
  height: 1000,
},
    {
    slug: "luma-dock",
    name: "LUMA DOCK",
    client: "Multifunctional desk lamp",
    description: "A multifunctional desk lamp featuring an integrated adhesive storage surface for keeping small essentials organized within easy reach.",
    url: "products/luma_dock.png",
    width: 487,
    height: 319,
  },

  {
    slug: "vayu",
    name: "VAYU",
    client: "Smart Air Purifier",
    description: "VAYU is a lifestyle integrated air purifier that combines intuitive physical feedback, automation, and seamless spatial integration to transform air purification into an effortless everyday experience.",
    url: "products/vayu.png",
    width: 487,
    height: 319,
  },

];